export type Tag =
  "BTS"
  | "Birthmark left inner thigh"
  | "Speaking French"
  | "blue vintage bug"
  | "Elbow Birthmark"
  | "Sybian"
  | "Cuckhold"
  | "Spanking"
  | "Standing 69"
  | "Winking"
  | "Cum on Pussy"
  | "Side Fuck"
  | "Side Rider"
  | "Candid"
  | "Cheating"
  | "Face Fuck"
  | "Analingus"
  | "Pussy to Mouth"
  | "Neck Tattoo"
  | "No Make up"
  | "Bruise left outer Hip"
  | "Boy/Boy/Boy/Girl"
  | "Boy/Girl/Girl"
  | "Boy/Girl"
  | "T-Girl/Girl"
  | "Girl/Girl"
  | "Girl/Girl/Girl"
  | "Girl/Girl/Boy"
  | "Strap-on"
  | "Pantyhose"
  | "Stilettos"
  | "Heel Fetish"
  | "Solo"
  | "Cage"
  | "Facial"
  | "Vaginal"
  | "Doggy"
  | "Cowgirl"
  | "Reverse Cowgirl"
  | "Square Buttons"
  | "Cunnilingus"
  | "Face Sitting"
  | "Creampie"
  | "Anal Creampie"
  | "Cuddling"
  | "Wrestling"
  | "Blowjob"
  | "69"
  | "Deepthroat"
  | "Roleplay"
  | "Missionary"
  | "Finger in Butt"
  | "Feet"
  | "Submission"
  | "Domination"
  | "Blonde"
  | "POV"
  | "Multiple Orgasms"
  | "Titty Fuck"
  | "Lingerie"
  | "Hitachi"
  | "Vibrator"
  | "Water"
  | "Outside"
  | "Dildo"
  | "Anal"
  | "Standing"
  | "On Chair"
  | "On Bed"
  | "On Couch"
  | "On Stairs"
  | "On Desk"
  | "Public"
  | "Dog"
  | "Tribbing"
  | "Ass to Mouth"
  | "Interracial"
  | "Stockings"
  | "Squirt"
  | "Threesome"
  | "Bodysuite"
  | "Bath"
  | "Jewellery"
  | "Choking"
  | "Biting"
  | "Bush"
  | "Tit Sucking 69"
  | "Smothering"
  | "Hurt Knee"
  | "Hicky"
  | "Picture-In-Picture"
  | "Against Wall"
  | "VR"
  | "Acting"
  | "Comedy"
  | "Live Stream"
  | "Ice Cream"
  | "Gloryhole"
  | "Orgy"
  | "Double Penetration"
  | "DP"
  | "Triple Penetration"
  | "TP"
  | "Double Vag"
  | "DV"
  | "Double Anal"
  | "DA"
  | "Foursome"
  | "Fisting"
  | "Trans"
  | "Genuine Feelings"
  | "BDSM"
  | "Rope"
  | "Suspention"
  | "Cane"
  | "Ball Gag"
  | "Nipple Clamps"
  | "Bastinado"
  | "Blackmail"
  | "Sweat"
  | "Kitchen"
  | "Feeding"
  | "Dirty Talk"
  | "Lube"
  | "Fishnet"
  | "Ass to Pussy"
  | "Cum on Tits"
  | "JAV";
