export type Tag =
  'BTS'
  | 'Birthmark Left Inner Thigh'
  | 'Speaking French'
  | 'blue vintage bug'
  | 'Elbow Birthmark'
  | 'Sybian'
  | 'Cuckhold'
  | 'Spanking'
  | 'Standing 69'
  | 'Winking'
  | 'Cum on Pussy'
  | 'Side Fuck'
  | 'Glasses'
  | 'Side-Saddle Cowgirl'
  | 'Candid'
  | 'Spit'
  | 'Rubberbands'
  | 'Whipping'
  | 'Clamps'
  | 'Cheating'
  | 'Face Fuck'
  | 'Anilingus'
  | 'Footjob'
  | 'Pussy to Mouth'
  | 'Neck Tattoo'
  | 'No Makeup'
  | 'Bruise left outer Hip'
  | 'Boy/Boy/Boy/Girl'
  | 'Girls only'
  | 'Boy/Boy/Girl'
  | 'Boy/Girl/Girl'
  | 'Boy/Girl'
  | 'T-Girl/Girl'
  | 'Girl/Girl'
  | 'Girl/Girl/Girl'
  | 'Girl/Girl/Boy'
  | 'Strap-on'
  | 'Pantyhose'
  | 'Stilettos'
  | 'Heel Fetish'
  | 'Solo'
  | 'Gaping'
  | 'Cage'
  | 'Facial'
  | 'Vaginal'
  | 'Doggy'
  | 'Cowgirl'
  | 'Reverse Cowgirl'
  | 'Oil'
  | 'Squirt Foutain'
  | 'Mouth to Mouth'
  | 'Square Buttons'
  | 'Cunnilingus'
  | 'Spooning'
  | 'Face Sitting'
  | 'Creampie'
  | 'Anal Creampie'
  | 'Cuddling'
  | 'Wrestling'
  | 'Blowjob'
  | '69'
  | 'Deepthroat'
  | 'Switching Holes'
  | 'Fauxcest'
  | 'Roleplay'
  | 'Missionary'
  | 'Finger in Butt'
  | 'Fingering'
  | 'Off the Ground'
  | 'Leash'
  | 'Key Necklace'
  | 'Clothed'
  | 'Panty Gag'
  | 'Feet'
  | 'Submission'
  | 'Domination'
  | 'Blond'
  | 'POV'
  | 'Multiple Orgasms'
  | 'Titty Fuck'
  | 'Lingerie'
  | 'Hitachi'
  | 'Vibrator'
  | 'Water'
  | 'Outside'
  | 'Dildo'
  | 'Anal'
  | 'Standing'
  | 'On Chair'
  | 'On Bed'
  | 'On Couch'
  | 'On Stairs'
  | 'On Desk'
  | 'Public'
  | 'Dog'
  | 'Tribbing'
  | 'Ass to Mouth'
  | 'Interracial'
  | 'Stockings'
  | 'Squirt'
  | 'Threesome'
  | 'Bodysuit'
  | 'Jeweled Butt Plug'
  | 'Bath'
  | 'Jewellery'
  | 'Choking'
  | 'Biting'
  | 'Bush'
  | 'Tit Sucking 69'
  | 'Smothering'
  | 'Hurt Knee'
  | 'Hicky'
  | 'Picture-In-Picture'
  | 'Against Wall'
  | 'VR'
  | 'Acting'
  | 'Comedy'
  | 'Live Stream'
  | 'Ice Cream'
  | 'Gloryhole'
  | 'Gangbang'
  | 'Blowbang'
  | 'Milkshake'
  | 'Double Penetration'
  | 'DP'
  | 'Triple Penetration'
  | 'TP'
  | 'Double Vaginal'
  | 'DV'
  | 'Double Anal'
  | 'DA'
  | 'Foursome'
  | 'Fisting'
  | 'Trans'
  | 'Genuine Feelings'
  | 'Shackles'
  | 'Rope Bondage'
  | 'Suspension'
  | 'Cane'
  | 'Ball Gag'
  | 'Nipple Clamps'
  | 'Bastinado'
  | 'Blackmail'
  | 'Sweat'
  | 'Kitchen'
  | 'Feeding'
  | 'Dirty Talk'
  | 'Lube'
  | 'Fishnet'
  | 'Ass to Pussy'
  | 'Pussy to Ass'
  | 'Cum on Tits'
  | 'Voyeur'
  | 'Instructions'
  | 'Pussy Stack'
  | 'Switching'
  | 'Pool'
  | 'AVN Best Gonzo Movie 2017'
  | 'AVN Best All-Girl Group Sex Scene 2016'
  | 'AVN Best Boy/Girl Sex Scene 2018'
  | 'AVN Best Double Penetration Sex Scene 2018'
  | 'AVN Best All-Girl Movie 2016'
  | 'AVN Best All-Girl Movie 2018'
  | 'AVN Best All-Girl Movie 2019'
  | 'AVN Best Drama 2019'
  | 'AVN Best Star Showcase 2018'
  | 'AVN Best Star Showcase 2019'
  | 'AVN Best Anal Sex Scene 2019'
  | 'AVN Best Threesome Girl/Girl/Boy 2019'
  | 'AVN Best Actress - Featurette 2019 (Angela White)'
  | 'AVN Best Actor - Featurette 2019 (Tommy Pistol)'
  | 'AVN Best Featurette 2019'
  | 'AVN Best Oral Sex Scene 2016'
  | 'AVN Best Oral Sex Scene 2019'
  | 'AVN Best Group Sex Scene 2018'
  | 'AVN Best Group Sex Scene 2019'
  | 'Jerk Off Instructions'
  | 'Panty Mail'
  | 'Handjob'
  | 'JAV';
